package constant;

public enum NameButtonForLogin {
    LOGIN_IN_USING_THE_IN_TO_ACCOUNT_BUTTON_ON_THR_HOME_PAGE,
    LOGIN_VIA_THE_PERSONAL_ACCOUNT_BUTTON,
    LOGIN_IN_VIA_THE_BUTTON_IN_THE_REGISTRATION_FORM,
    LOGIN_VIA_THE_BUTTON_IN_THE_PASSWORD_RECOVERY_FORM
}